# Generated by Django 2.0.5 on 2018-06-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djeet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djeet',
            name='body',
            field=models.CharField(max_length=140),
        ),
    ]
