# Generated by Django 2.0.5 on 2018-06-29 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djeet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djeet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='djeets', to=settings.AUTH_USER_MODEL),
        ),
    ]
