# Generated by Django 2.0.5 on 2018-06-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='Default Name', max_length=20),
        ),
    ]
