# Generated by Django 2.0.5 on 2018-06-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djeeterprofile', '0004_djeeterprofile_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djeeterprofile',
            name='profile',
        ),
    ]
